### ISSUE TITLE
Getting a 400 instead of 302 on postPasswordForm request

### ISSUE THREAD

**Issue by pschroeder89** [rlueder/node-car-net#2]
Hey @rlueder, is this still working for you? I updated the parseFormInputs in this branch to get the values, it looks like VW changed that. https://github.com/rlueder/node-car-net/pull/1

Even so, the request doesn't seem to work. It looks identical to what I see in the Charles app when I login to the my VW app. Any ideas would be helpful, thanks!

**Comment by rlueder** [comment]
hey @pschroeder89 it looks like VW updated yet again their login flow (which wasn't great to being with). I'll try and find some time in the next few days to see what's changed and hopefully we can get it to work again.
